name: Build and Push Docker Image

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Install kubectl
      uses: azure/setup-kubectl@v3.0
      with:
        version: 'v1.31.1' 
      id: install

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u rabbit0604 --password-stdin

    - name: Build Docker image
      run:  docker build -t test:latest .

    - name: Tag Docker image
      run:  docker tag test:latest rabbit0604/test:latest

    - name: Push Docker image
      run:  docker push rabbit0604/test:latest

    - name: List Docker images
      run:  docker images

    - name: Update kube config
      run: aws eks update-kubeconfig --name nova --region us-west-2

    - name: Deploy to EKS
      run: |
        cd test
        kubectl apply -f pod.yml
