name: Build and Push Docker Image

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log out from Docker (if needed)
      run: docker logout

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u rabbit0604 --password-stdin

    - name: Build Docker image
      run:  docker build -t test:latest .
      
    - name: check Docker image
      run:  docker images

    - name: Tag Docker image
      run:  docker tag test:latest rabbit0604/test:latest

    - name: check Docker image after tag
      run:  docker images

    - name: Push Docker image
      run:  docker push rabbit0604/test:latest

    - name: List Docker images
      run:  docker images
